#!/usr/bin/env python3
"""
Row-Level Security migration for the Rio CRM multi-tenant schema.

Usage
-----
# Step 4 — leads table only (test first before rolling out everywhere)
python migrations/apply_rls.py --table leads

# Step 5 — all tenant tables
python migrations/apply_rls.py --all

# Check current RLS status without changing anything
python migrations/apply_rls.py --status

The policy uses a NULL-bypass pattern:
  NULLIF(current_setting('app.current_company_id', true), '')::int

When the session variable is unset (migrations, health checks, webhooks):
  → NULLIF returns NULL → all rows visible  (admin / system bypass)

When the session variable is set to '42' by the RLS middleware:
  → NULLIF returns 42 → only company_id = 42 rows visible  (tenant isolation)
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

# Allow running from repo root or backend/
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from dotenv import load_dotenv

load_dotenv(Path(__file__).resolve().parents[1] / ".env", override=False)

import psycopg2  # direct psycopg2 for DDL — SQLModel doesn't handle CREATE POLICY

# Tables that have company_id and SHOULD have RLS
# Generated by: python -c "...SQLModel.metadata.tables..." (see exploration output)
# Tables WITHOUT company_id are intentionally excluded: companies, permissions, role_permissions, user_roles, user_settings

ALL_TENANT_TABLES: list[str] = [
    "accounts",
    "activity_events",
    "analytics_alerts",
    "appointments",
    "audit_logs",
    "background_jobs",
    "call_coach_scores",
    "call_status_events",
    "call_tasks",
    "campaign_recipients",
    "campaign_steps",
    "campaigns",
    "company_feature_flags",
    "company_settings",
    "company_usage",
    "competitor_mentions",
    "email_outbox",
    "engagement_events",
    "feedback",
    "feedback_public_audit",
    "interactions",
    "invites",
    "latencylog",
    "lead_requirements",
    "leads",
    "login_history",
    "message_templates",
    "objection_entries",
    "opt_outs",
    "outcomes",
    "products",
    "quote_items",
    "quotes",
    "roles",
    "sentiment_events",
    "users",
    "voice_agent_execution_events",
    "voice_agent_extraction_results",
    "voice_agent_extraction_templates",
    "voice_agent_graphs",
    "voice_agent_prompt_versions",
    "voice_agent_runtime_configs",
    "voice_agent_tools",
    "voice_agent_voice_presets",
    "voice_agents",
    "provider_phone_numbers",
    "campaign_schedules",
    "sip_trunks",
    "compliance_applications",
]

POLICY_NAME = "tenant_isolation"

# The policy expression — works for both SELECT and DML (USING + WITH CHECK)
_POLICY_EXPR = r"""
    NULLIF(current_setting('app.current_company_id', true), '')::int IS NULL
    OR company_id = NULLIF(current_setting('app.current_company_id', true), '')::int
""".strip()


def _connect() -> "psycopg2.connection":
    url = os.environ["DATABASE_URL"]
    return psycopg2.connect(url)


def table_exists(cur, table: str) -> bool:
    cur.execute(
        "SELECT 1 FROM information_schema.tables "
        "WHERE table_schema = 'public' AND table_name = %s",
        (table,),
    )
    return cur.fetchone() is not None


def rls_enabled(cur, table: str) -> bool:
    cur.execute(
        "SELECT relrowsecurity FROM pg_class "
        "WHERE relname = %s AND relnamespace = 'public'::regnamespace",
        (table,),
    )
    row = cur.fetchone()
    return bool(row and row[0])


def rls_forced(cur, table: str) -> bool:
    """Check whether FORCE ROW LEVEL SECURITY is set on the table."""
    cur.execute(
        "SELECT relforcerowsecurity FROM pg_class "
        "WHERE relname = %s AND relnamespace = 'public'::regnamespace",
        (table,),
    )
    row = cur.fetchone()
    return bool(row and row[0])


def policy_exists(cur, table: str, policy: str) -> bool:
    cur.execute(
        "SELECT 1 FROM pg_policies "
        "WHERE schemaname = 'public' AND tablename = %s AND policyname = %s",
        (table, policy),
    )
    return cur.fetchone() is not None


def enable_rls_on_table(cur, table: str, verbose: bool = True) -> None:
    if not table_exists(cur, table):
        print(f"  SKIP  {table!r} — table does not exist yet")
        return

    # Enable RLS + FORCE so policies apply even when connected as the table owner.
    # Without FORCE, Postgres silently bypasses RLS for the owner role, which
    # means tenant isolation has no effect if the app connects as the owner.
    if not rls_enabled(cur, table):
        cur.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY')
        if verbose:
            print(f"  ENABLE RLS  {table}")
    else:
        if verbose:
            print(f"  ALREADY     {table} (RLS was already enabled)")

    cur.execute(f'ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY')

    # Create policy (idempotent — drop+recreate if exists so re-runs are safe)
    if policy_exists(cur, table, POLICY_NAME):
        cur.execute(f'DROP POLICY "{POLICY_NAME}" ON "{table}"')

    cur.execute(
        f'CREATE POLICY "{POLICY_NAME}" ON "{table}" '
        f"USING ({_POLICY_EXPR}) "
        f"WITH CHECK ({_POLICY_EXPR})"
    )
    if verbose:
        print(f"  POLICY      {table}.{POLICY_NAME} created")


def apply_rls(tables: list[str]) -> None:
    conn = _connect()
    conn.autocommit = False
    cur = conn.cursor()
    try:
        print(f"\nApplying RLS to {len(tables)} table(s)...\n")
        for table in tables:
            enable_rls_on_table(cur, table)
        conn.commit()
        print(f"\nDone. {len(tables)} table(s) processed.")
    except Exception as exc:
        conn.rollback()
        print(f"\nERROR — rolled back: {exc}")
        sys.exit(1)
    finally:
        cur.close()
        conn.close()


def ensure_rls(verbose: bool = False) -> None:
    """
    Idempotent, non-interactive version of apply_rls(ALL_TENANT_TABLES).
    Safe to call on every server startup — skips tables that are already
    protected and silently handles missing tables (new migrations not yet run).
    """
    import logging
    _log = logging.getLogger(__name__)

    conn = _connect()
    conn.autocommit = False
    cur = conn.cursor()
    applied = skipped = 0
    try:
        for table in ALL_TENANT_TABLES:
            if not table_exists(cur, table):
                _log.debug("rls: table %r does not exist yet — skipping", table)
                continue
            already_on = rls_enabled(cur, table)
            already_has_policy = policy_exists(cur, table, POLICY_NAME)
            already_forced = rls_forced(cur, table)
            if already_on and already_has_policy and already_forced:
                skipped += 1
                continue
            enable_rls_on_table(cur, table, verbose=verbose)
            applied += 1
        conn.commit()
        if applied:
            _log.info("RLS applied on startup", extra={
                "event": "rls_applied",
                "tables_updated": applied,
                "tables_skipped": skipped,
            })
        else:
            _log.debug("rls: all %d tables already protected", skipped)
    except Exception as exc:
        conn.rollback()
        _log.error("RLS startup apply failed — rolled back: %s", exc)
        raise
    finally:
        cur.close()
        conn.close()


def print_status() -> None:
    conn = _connect()
    conn.autocommit = True
    cur = conn.cursor()
    print(f"\n{'Table':<30} {'RLS':^6} {'FORCE':^7} {'Policy':^10}")
    print("-" * 57)
    for table in ALL_TENANT_TABLES:
        if not table_exists(cur, table):
            print(f"  {table:<28} {'?':^6} {'?':^7} {'(missing)':^10}")
            continue
        enabled = rls_enabled(cur, table)
        forced = rls_forced(cur, table)
        has_policy = policy_exists(cur, table, POLICY_NAME)
        rls_str   = "ON " if enabled    else "off"
        force_str = "ON " if forced     else "OFF"
        pol_str   = "yes" if has_policy  else "no"
        print(f"  {table:<28} {rls_str:^6} {force_str:^7} {pol_str:^10}")
    cur.close()
    conn.close()


def main() -> None:
    parser = argparse.ArgumentParser(description="Apply Postgres RLS to tenant tables")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--table", metavar="NAME", help="Apply RLS to a single table (e.g. --table leads)")
    group.add_argument("--all",   action="store_true", help="Apply RLS to all 36 tenant tables")
    group.add_argument("--status", action="store_true", help="Print current RLS status without changes")
    args = parser.parse_args()

    if args.status:
        print_status()
    elif args.table:
        if args.table not in ALL_TENANT_TABLES:
            print(f"WARNING: {args.table!r} is not in the known tenant table list.")
            print("Known tables:", ", ".join(ALL_TENANT_TABLES))
            ans = input("Continue anyway? [y/N] ")
            if ans.lower() != "y":
                sys.exit(0)
        apply_rls([args.table])
    elif args.all:
        print("This will enable RLS on ALL 36 tenant tables.")
        ans = input("Type 'yes' to confirm: ")
        if ans.strip().lower() != "yes":
            print("Aborted.")
            sys.exit(0)
        apply_rls(ALL_TENANT_TABLES)


if __name__ == "__main__":
    main()
