import {
  Sun, Mail, Brain, Zap, KeyRound, Database, Webhook, Layers,
  ShieldCheck, CheckCircle2, Sparkles, Gauge, Server, Users2,
  PhoneForwarded, Settings2, Calendar, BarChart3, Network, Package,
} from "lucide-react";
import type { SectionDef } from "./SettingsCard";

export const SECTION_DEFS: SectionDef[] = [
  // ── Your Account ─────────────────────────────────
  {
    id: "profile",
    label: "Profile & Appearance",
    description: "Theme, My Rio Persona, verbosity",
    icon: Sun,
    group: "account",
    iconGradient: "from-yellow-400 to-orange-500",
  },
  {
    id: "my_email",
    label: "My Email",
    description: "Personal SMTP / IMAP & warm transfer",
    icon: Mail,
    group: "account",
    iconGradient: "from-blue-400 to-cyan-500",
  },

  // ── Company ──────────────────────────────────────
  {
    id: "voice_ai",
    label: "Voice & AI Engine",
    description: "STT, LLM, TTS providers · system prompt · prompt versions",
    icon: Brain,
    group: "company",
    iconGradient: "from-violet-500 to-purple-600",
    adminOnly: true,
  },
  {
    id: "telephony_config",
    label: "Telephony & Voice Config",
    description: "Engine, business hours, silence re-engage, ambient noise, ASR, agent greetings, calendar",
    icon: PhoneForwarded,
    group: "company",
    iconGradient: "from-blue-500 to-indigo-600",
    adminOnly: true,
  },
  {
    id: "agent_templates",
    label: "Agent Templates",
    description: "Deploy pre-built voice agent blueprints",
    icon: Sparkles,
    group: "company",
    iconGradient: "from-pink-500 to-rose-500",
    adminOnly: true,
  },

  // ── Integrations ─────────────────────────────────
  {
    id: "api_keys",
    label: "Integration Keys",
    description: "API credentials for STT, LLM, TTS, telephony, email providers",
    icon: KeyRound,
    group: "integrations",
    iconGradient: "from-emerald-400 to-green-600",
    adminOnly: true,
  },
  {
    id: "credentials",
    label: "Provider Credentials",
    description: "Encrypted per-provider key/value store",
    icon: Database,
    group: "integrations",
    iconGradient: "from-teal-400 to-emerald-600",
    adminOnly: true,
  },
  {
    id: "integrations",
    label: "No-Code Integrations",
    description: "Zapier, Make.com, n8n · event payload sandbox",
    icon: Zap,
    group: "integrations",
    iconGradient: "from-amber-400 to-orange-500",
    adminOnly: true,
  },
  {
    id: "webhooks",
    label: "Webhooks",
    description: "Register outbound endpoints for CRM events",
    icon: Webhook,
    group: "integrations",
    iconGradient: "from-blue-500 to-indigo-600",
    adminOnly: true,
  },
  {
    id: "mcp_connections",
    label: "MCP Connections",
    description: "Connect Apollo, Zoho, and custom MCP servers",
    icon: Network,
    group: "integrations",
    iconGradient: "from-violet-500 to-fuchsia-600",
    adminOnly: true,
  },
  {
    id: "inventory_sources",
    label: "Inventory Sources",
    description: "Pluggable product inventory: catalog, CSV, ERP API",
    icon: Package,
    group: "integrations",
    iconGradient: "from-green-500 to-teal-600",
    adminOnly: true,
  },

  // ── Operations ───────────────────────────────────
  {
    id: "sub_accounts",
    label: "Sub Accounts",
    description: "Create & manage child accounts, concurrency, caps",
    icon: Layers,
    group: "operations",
    iconGradient: "from-slate-500 to-slate-700",
    adminOnly: true,
  },
  {
    id: "compliance",
    label: "Compliance & DLT",
    description: "DLT registrations, Truecaller brand verification",
    icon: ShieldCheck,
    group: "operations",
    iconGradient: "from-red-500 to-rose-600",
    adminOnly: true,
  },
  {
    id: "dispositions",
    label: "Outcome Dispositions",
    description: "Call outcome triggers · live predictor / LLM judge",
    icon: CheckCircle2,
    group: "operations",
    iconGradient: "from-green-500 to-emerald-600",
    adminOnly: true,
  },
  {
    id: "cost",
    label: "Cost & Billing",
    description: "Usage costs, daily summaries, custom provider rates",
    icon: BarChart3,
    group: "operations",
    iconGradient: "from-violet-500 to-indigo-600",
    adminOnly: true,
  },
  {
    id: "feature_flags",
    label: "Feature Flags & Worker",
    description: "Toggle features · automation worker status",
    icon: Settings2,
    group: "operations",
    iconGradient: "from-orange-400 to-amber-500",
    adminOnly: true,
  },
  {
    id: "sip_trunks",
    label: "SIP Trunks",
    description: "External SIP trunk configurations for telephony routing",
    icon: Server,
    group: "operations",
    iconGradient: "from-orange-500 to-red-600",
    adminOnly: true,
  },
  {
    id: "usage",
    label: "Usage Limits",
    description: "Monthly caps for calls, emails, WhatsApp",
    icon: Gauge,
    group: "operations",
    iconGradient: "from-cyan-500 to-blue-600",
    adminOnly: true,
  },
  {
    id: "competitors",
    label: "Competitors",
    description: "Live detection & counter-scripts injected during calls",
    icon: Users2,
    group: "operations",
    iconGradient: "from-rose-400 to-red-500",
    adminOnly: true,
  },
];
